version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pwd  # Debug: Print current directory
      - ls -la  # Debug: List directory contents
  build:
    commands:
      - echo "Running tests if any..."
      # Add your test commands here if needed
  post_build:
    commands:
      # Create function package (without dependencies)
      - echo "Preparing Lambda function package..."
      - mkdir -p function-package
      - cp -r app function-package/ || exit 1
      - cp lambda_function.py function-package/ || exit 1
      - cp lambda_handler.py function-package/ || exit 1
      - cd function-package
      - zip -r ../function.zip . || exit 1
      - cd ..

      # Create layer package (only dependencies)
      - echo "Preparing Lambda layer package..."
      - mkdir -p layer/python
      - cd layer/python
      - pip install -r ../../requirements.txt -t . || exit 1
      - cd ..
      - zip -r ../layer.zip . || exit 1
      - cd ..

      # Debug output
      - echo "Listing artifacts:"
      - ls -la *.zip
      - echo "Content of function.zip:"
      - unzip -l function.zip
      - echo "Content of layer.zip:"
      - unzip -l layer.zip

artifacts:
  files:
    - function.zip
    - layer.zip  discard-paths: yes
